# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6725665c5e31b689dbd72583f9f556a8ce43244cd2e52884436606c7c3909d7a38daaa353fc3e55627ee576292ecbd9b7da7b3817ef867c91f7f3d820ba756b7

test:
  secret_key_base: 24fe5ebc84b27ce41ec414c0e4f118fb382feb3becdfe4ee2302874073f4d681eb12c182c44ad4b1c65ddb3586fcc700a2db442f9fff771bd226c50393efd43d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
